name: microblog
channels:
- conda-forge
- defaults
dependencies:
- alembic=0.9.6=py_0
- flask-migrate=2.1.1=py36_0
- flask-sqlalchemy=2.3.2=py_0
- mako=1.0.7=py36_0
- python-dateutil=2.6.1=py36_0
- python-editor=1.0.3=py36_0
- six=1.11.0=py36_1
- sqlalchemy=1.1.13=py36_0
- certifi
- click
- flask
- flask-wtf=0.14.2=py36_0
- itsdangerous
- jinja2
- markupsafe
- pip
- python=3.6
- setuptools
- werkzeug
- wheel
- wtforms=2.1=py36_0
- flask-wtf
